"""feat: SchlagKultur – sorte, saatmenge-Felder fuer Saat-Wizard

Revision ID: 22a8ef55648f
Revises: e1f2g3h4
Create Date: 2026-03-17 21:15:47.158590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22a8ef55648f'
down_revision = 'e1f2g3h4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betrieb', schema=None) as batch_op:
        batch_op.alter_column('modul_ackerbau',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('modul_ackerbau_pro',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('duengebedarfsermittlung', schema=None) as batch_op:
        batch_op.alter_column('ist_rotes_gebiet',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('duengung', schema=None) as batch_op:
        batch_op.alter_column('einarbeitung',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
        batch_op.drop_index(batch_op.f('ix_duengung_schlag_id'))

    with op.batch_alter_table('schlag', schema=None) as batch_op:
        batch_op.alter_column('aktiv',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_schlag_betrieb_id'))

    with op.batch_alter_table('schlag_kultur', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sorte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('saatmenge_kg_ha', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.add_column(sa.Column('saatmenge_tatsaechlich_kg_ha', sa.Numeric(precision=8, scale=2), nullable=True))
        batch_op.drop_index(batch_op.f('ix_schlag_kultur_schlag_id'))

    with op.batch_alter_table('spritzmittel', schema=None) as batch_op:
        batch_op.alter_column('aktiv',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.drop_index(batch_op.f('ix_spritzmittel_betrieb_id'))

    with op.batch_alter_table('spritzung', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spritzung_datum'))
        batch_op.drop_index(batch_op.f('ix_spritzung_schlag_id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spritzung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spritzung_schlag_id'), ['schlag_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spritzung_datum'), ['datum'], unique=False)

    with op.batch_alter_table('spritzmittel', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_spritzmittel_betrieb_id'), ['betrieb_id'], unique=False)
        batch_op.alter_column('aktiv',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('schlag_kultur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schlag_kultur_schlag_id'), ['schlag_id'], unique=False)
        batch_op.drop_column('saatmenge_tatsaechlich_kg_ha')
        batch_op.drop_column('saatmenge_kg_ha')
        batch_op.drop_column('sorte')

    with op.batch_alter_table('schlag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_schlag_betrieb_id'), ['betrieb_id'], unique=False)
        batch_op.alter_column('aktiv',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('duengung', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duengung_schlag_id'), ['schlag_id'], unique=False)
        batch_op.alter_column('einarbeitung',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('duengebedarfsermittlung', schema=None) as batch_op:
        batch_op.alter_column('ist_rotes_gebiet',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    with op.batch_alter_table('betrieb', schema=None) as batch_op:
        batch_op.alter_column('modul_ackerbau_pro',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
        batch_op.alter_column('modul_ackerbau',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))

    # ### end Alembic commands ###
