"""Betrieb: waehrung, mwst_satz_standard, uid_format

Revision ID: 49f21319ac9f
Revises: 5e6fbd316e14
Create Date: 2026-03-11 18:29:47.894466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f21319ac9f'
down_revision = '5e6fbd316e14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betrieb', sa.Column('waehrung', sa.String(length=5), nullable=True))
    op.add_column('betrieb', sa.Column('mwst_satz_standard', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('betrieb', sa.Column('uid_format', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('betrieb', 'uid_format')
    op.drop_column('betrieb', 'mwst_satz_standard')
    op.drop_column('betrieb', 'waehrung')
    # ### end Alembic commands ###
