"""Phase 2: Buchhaltung, Fakturierung, Lager

Revision ID: 5e6fbd316e14
Revises: 
Create Date: 2026-03-11 18:19:48.690478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e6fbd316e14'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('betrieb',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=120), nullable=True),
    sa.Column('land', sa.String(length=2), nullable=True),
    sa.Column('uid_nummer', sa.String(length=20), nullable=True),
    sa.Column('steuernummer', sa.String(length=20), nullable=True),
    sa.Column('iban', sa.String(length=34), nullable=True),
    sa.Column('bic', sa.String(length=11), nullable=True),
    sa.Column('bank_name', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('website', sa.String(length=255), nullable=True),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('hintergrundbild_path', sa.String(length=255), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kategorie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('farbe', sa.String(length=7), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('konto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.String(length=20), nullable=False),
    sa.Column('bezeichnung', sa.String(length=255), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nummer')
    )
    op.create_table('kunde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('strasse', sa.String(length=255), nullable=True),
    sa.Column('plz', sa.String(length=10), nullable=True),
    sa.Column('ort', sa.String(length=120), nullable=True),
    sa.Column('land', sa.String(length=2), nullable=True),
    sa.Column('uid_nummer', sa.String(length=20), nullable=True),
    sa.Column('kontakt', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lagerartikel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('artikelnummer', sa.String(length=50), nullable=True),
    sa.Column('einheit', sa.String(length=20), nullable=True),
    sa.Column('aktueller_bestand', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('mindestbestand', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('letzter_einkaufspreis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('durchschnittswert', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artikelnummer')
    )
    op.create_table('maschine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('kennzeichen', sa.String(length=50), nullable=True),
    sa.Column('baujahr', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('gesperrt', sa.Boolean(), nullable=True),
    sa.Column('sperrgrund', sa.Text(), nullable=True),
    sa.Column('buchungsmodus', sa.String(length=20), nullable=True),
    sa.Column('zaehler_format', sa.String(length=20), nullable=True),
    sa.Column('kosten_pro_einheit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('einheit', sa.String(length=50), nullable=True),
    sa.Column('anschaffungswert', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('anschaffungsdatum', sa.Date(), nullable=True),
    sa.Column('abschreibungsdauer', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('vorname', sa.String(length=120), nullable=True),
    sa.Column('nachname', sa.String(length=120), nullable=True),
    sa.Column('telefon', sa.String(length=20), nullable=True),
    sa.Column('rolle', sa.String(length=20), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('letzter_login', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('buchung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('valuta', sa.Date(), nullable=True),
    sa.Column('soll_konto_id', sa.Integer(), nullable=True),
    sa.Column('haben_konto_id', sa.Integer(), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('kategorie_id', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=False),
    sa.Column('beleg_nummer', sa.String(length=50), nullable=True),
    sa.Column('mwst_satz', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mwst_betrag', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('bezahlt', sa.Boolean(), nullable=True),
    sa.Column('erstellt_von_id', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['erstellt_von_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['haben_konto_id'], ['konto.id'], ),
    sa.ForeignKeyConstraint(['kategorie_id'], ['kategorie.id'], ),
    sa.ForeignKeyConstraint(['soll_konto_id'], ['konto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('einsatz',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maschine_id', sa.Integer(), nullable=False),
    sa.Column('erstellt_von_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('von', sa.Time(), nullable=True),
    sa.Column('bis', sa.Time(), nullable=True),
    sa.Column('menge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('zaehlerstand_start', sa.String(length=50), nullable=True),
    sa.Column('zaehlerstand_ende', sa.String(length=50), nullable=True),
    sa.Column('kostenart', sa.String(length=50), nullable=True),
    sa.Column('kosten', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['erstellt_von_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['maschine_id'], ['maschine.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lagerbewegung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artikel_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('typ', sa.String(length=20), nullable=False),
    sa.Column('menge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grund', sa.String(length=20), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('benutzer_id', sa.Integer(), nullable=True),
    sa.Column('beleg_nummer', sa.String(length=50), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artikel_id'], ['lagerartikel.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['benutzer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rechnung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nummer', sa.String(length=50), nullable=False),
    sa.Column('kunde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('faellig_am', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('netto_gesamt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('mwst_gesamt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brutto_gesamt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notiz', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nummer')
    )
    op.create_table('rechnungsposition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rechnung_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('beschreibung', sa.String(length=255), nullable=False),
    sa.Column('menge', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('einheit', sa.String(length=20), nullable=True),
    sa.Column('einzelpreis', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('mwst_satz', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('netto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mwst', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('brutto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['rechnung_id'], ['rechnung.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rechnungsposition')
    op.drop_table('rechnung')
    op.drop_table('lagerbewegung')
    op.drop_table('einsatz')
    op.drop_table('buchung')
    op.drop_table('user')
    op.drop_table('maschine')
    op.drop_table('lagerartikel')
    op.drop_table('kunde')
    op.drop_table('konto')
    op.drop_table('kategorie')
    op.drop_table('betrieb')
    # ### end Alembic commands ###
