"""Add legehennen module

Revision ID: 6cda0ebf1e72
Revises: c5d231268061
Create Date: 2026-03-13 22:07:24.383366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cda0ebf1e72'
down_revision = 'c5d231268061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('herde',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rasse', sa.String(length=100), nullable=True),
    sa.Column('haltungsform', sa.Integer(), nullable=True),
    sa.Column('schlupfdatum', sa.Date(), nullable=True),
    sa.Column('lieferdatum', sa.Date(), nullable=True),
    sa.Column('lieferant', sa.String(length=200), nullable=True),
    sa.Column('lieferant_vvvo', sa.String(length=50), nullable=True),
    sa.Column('anfangsbestand', sa.Integer(), nullable=False),
    sa.Column('aktueller_bestand', sa.Integer(), nullable=True),
    sa.Column('stall_nr', sa.String(length=50), nullable=True),
    sa.Column('stall_flaeche_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('auslauf_flaeche_m2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('nest_plaetze', sa.Integer(), nullable=True),
    sa.Column('erzeuger_code', sa.String(length=20), nullable=True),
    sa.Column('legebeginn', sa.Date(), nullable=True),
    sa.Column('erwartetes_ende', sa.Date(), nullable=True),
    sa.Column('ausstalldatum', sa.Date(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('futter_lieferung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('futtermittel', sa.String(length=200), nullable=True),
    sa.Column('lieferant', sa.String(length=200), nullable=True),
    sa.Column('menge_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('charge', sa.String(length=100), nullable=True),
    sa.Column('preis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('herde_ereignis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('kategorie', sa.String(length=50), nullable=True),
    sa.Column('beschreibung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('impfung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('impfstoff', sa.String(length=200), nullable=True),
    sa.Column('krankheit', sa.String(length=100), nullable=True),
    sa.Column('charge', sa.String(length=100), nullable=True),
    sa.Column('verabreichungsart', sa.String(length=50), nullable=True),
    sa.Column('tierarzt', sa.String(length=200), nullable=True),
    sa.Column('naechste_impfung', sa.Date(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medikament_behandlung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('beginn', sa.Date(), nullable=False),
    sa.Column('ende', sa.Date(), nullable=True),
    sa.Column('medikament_name', sa.String(length=200), nullable=False),
    sa.Column('wirkstoff', sa.String(length=200), nullable=True),
    sa.Column('typ', sa.String(length=50), nullable=True),
    sa.Column('charge', sa.String(length=100), nullable=True),
    sa.Column('dosierung', sa.String(length=100), nullable=True),
    sa.Column('verabreichungsart', sa.String(length=50), nullable=True),
    sa.Column('diagnose', sa.String(length=200), nullable=True),
    sa.Column('tierarzt', sa.String(length=200), nullable=True),
    sa.Column('anzahl_tiere', sa.Integer(), nullable=True),
    sa.Column('wartezeit_tage', sa.Integer(), nullable=True),
    sa.Column('wartezeit_ende', sa.Date(), nullable=True),
    sa.Column('ist_antibiotikum', sa.Boolean(), nullable=True),
    sa.Column('beleg_nr', sa.String(length=50), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('salmonellen_probe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('probenart', sa.String(length=50), nullable=True),
    sa.Column('labor', sa.String(length=200), nullable=True),
    sa.Column('ergebnis', sa.String(length=20), nullable=True),
    sa.Column('serotyp', sa.String(length=100), nullable=True),
    sa.Column('beleg_nr', sa.String(length=100), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sortierergebnis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('eier_gesamt', sa.Integer(), nullable=True),
    sa.Column('groesse_s', sa.Integer(), nullable=True),
    sa.Column('groesse_m', sa.Integer(), nullable=True),
    sa.Column('groesse_l', sa.Integer(), nullable=True),
    sa.Column('groesse_xl', sa.Integer(), nullable=True),
    sa.Column('aussortiert', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tagesleistung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('eier_gesamt', sa.Integer(), nullable=True),
    sa.Column('eier_verkaufsfaehig', sa.Integer(), nullable=True),
    sa.Column('eier_knick', sa.Integer(), nullable=True),
    sa.Column('eier_bruch', sa.Integer(), nullable=True),
    sa.Column('eier_schmutzig', sa.Integer(), nullable=True),
    sa.Column('eier_wind', sa.Integer(), nullable=True),
    sa.Column('eier_boden', sa.Integer(), nullable=True),
    sa.Column('eigewicht_durchschnitt', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tierbestand', sa.Integer(), nullable=True),
    sa.Column('verluste', sa.Integer(), nullable=True),
    sa.Column('verlust_ursache', sa.String(length=200), nullable=True),
    sa.Column('futterverbrauch_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('wasserverbrauch_l', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('temperatur_stall', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('luftfeuchtigkeit', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('lichtprogramm_std', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tierarzt_besuch',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('herde_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('tierarzt_name', sa.String(length=200), nullable=True),
    sa.Column('tierarzt_praxis', sa.String(length=200), nullable=True),
    sa.Column('grund', sa.String(length=200), nullable=True),
    sa.Column('diagnose', sa.Text(), nullable=True),
    sa.Column('massnahmen', sa.Text(), nullable=True),
    sa.Column('naechster_besuch', sa.Date(), nullable=True),
    sa.Column('kosten', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['herde_id'], ['herde.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('packstelle_name', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('packstelle_ort', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('packstelle_nr', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('packstelle_nr')
        batch_op.drop_column('packstelle_ort')
        batch_op.drop_column('packstelle_name')

    op.drop_table('tierarzt_besuch')
    op.drop_table('tagesleistung')
    op.drop_table('sortierergebnis')
    op.drop_table('salmonellen_probe')
    op.drop_table('medikament_behandlung')
    op.drop_table('impfung')
    op.drop_table('herde_ereignis')
    op.drop_table('futter_lieferung')
    op.drop_table('herde')
    # ### end Alembic commands ###
