"""salmonellen_probe: datum->probenahme_datum, +ergebnis_datum, +massnahmen

Revision ID: 6dbb8fee6795
Revises: 6cda0ebf1e72
Create Date: 2026-03-14 06:46:01.921020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dbb8fee6795'
down_revision = '6cda0ebf1e72'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salmonellen_probe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('probenahme_datum', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('ergebnis_datum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('massnahmen', sa.Text(), nullable=True))
        batch_op.drop_column('datum')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('salmonellen_probe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('datum', sa.DATE(), autoincrement=False, nullable=False))
        batch_op.drop_column('massnahmen')
        batch_op.drop_column('ergebnis_datum')
        batch_op.drop_column('probenahme_datum')

    # ### end Alembic commands ###
