"""user: +muss_passwort_aendern

Revision ID: 8286c91bc26c
Revises: 8a71350b55c1
Create Date: 2026-03-14 12:13:38.285848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8286c91bc26c'
down_revision = '8a71350b55c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('muss_passwort_aendern', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('muss_passwort_aendern')

    # ### end Alembic commands ###
