"""betrieb: ist_testbetrieb + modul_legehennen

Revision ID: 90b458953577
Revises: 6dbb8fee6795
Create Date: 2026-03-14 11:53:26.743971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b458953577'
down_revision = '6dbb8fee6795'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betrieb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ist_testbetrieb', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('modul_legehennen', sa.Boolean(), nullable=True))

    with op.batch_alter_table('herde_ereignis', schema=None) as batch_op:
        batch_op.add_column(sa.Column('massnahmen', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('bemerkung', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('herde_ereignis', schema=None) as batch_op:
        batch_op.drop_column('bemerkung')
        batch_op.drop_column('massnahmen')

    with op.batch_alter_table('betrieb', schema=None) as batch_op:
        batch_op.drop_column('modul_legehennen')
        batch_op.drop_column('ist_testbetrieb')

    # ### end Alembic commands ###
