"""milchvieh phase2: besamung, mlp, euter, klauen, weide, tankmilch + laktation erweitert

Revision ID: a6327bd1caa5
Revises: d66b05281647
Create Date: 2026-03-14 18:32:45.245485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6327bd1caa5'
down_revision = 'd66b05281647'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tankmilch_auswertung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jahr', sa.Integer(), nullable=False),
    sa.Column('monat', sa.Integer(), nullable=False),
    sa.Column('milchmenge_kg', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fett_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('eiweiss_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('gesamtkeimzahl', sa.Integer(), nullable=True),
    sa.Column('zellzahl_tank', sa.Integer(), nullable=True),
    sa.Column('gefrierpunkt', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('hemmstoff', sa.Boolean(), nullable=True),
    sa.Column('auszahlungspreis_ct_kg', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('qualitaetszuschlag_ct', sa.Numeric(precision=5, scale=3), nullable=True),
    sa.Column('molkerei', sa.String(length=100), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('weide_periode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datum_von', sa.Date(), nullable=False),
    sa.Column('datum_bis', sa.Date(), nullable=True),
    sa.Column('weide_bezeichnung', sa.String(length=200), nullable=True),
    sa.Column('weide_flaeche_ha', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('anzahl_tiere', sa.Integer(), nullable=True),
    sa.Column('tier_gruppe', sa.String(length=100), nullable=True),
    sa.Column('stunden_pro_tag', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('besamung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('laktation_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('art', sa.String(length=30), nullable=True),
    sa.Column('stier_name', sa.String(length=100), nullable=True),
    sa.Column('stier_hb_nr', sa.String(length=50), nullable=True),
    sa.Column('portion_nr', sa.String(length=50), nullable=True),
    sa.Column('besamungstechniker', sa.String(length=100), nullable=True),
    sa.Column('td_datum', sa.Date(), nullable=True),
    sa.Column('traechtig', sa.Boolean(), nullable=True),
    sa.Column('td_methode', sa.String(length=50), nullable=True),
    sa.Column('tierarzt_td', sa.String(length=100), nullable=True),
    sa.Column('errechneter_kalbetermin', sa.Date(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laktation_id'], ['laktation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('euter_gesundheit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('euterviertel', sa.String(length=10), nullable=True),
    sa.Column('schalmtest', sa.String(length=10), nullable=True),
    sa.Column('zellzahl_tsd', sa.Integer(), nullable=True),
    sa.Column('erreger', sa.String(length=100), nullable=True),
    sa.Column('mastitis_typ', sa.String(length=20), nullable=True),
    sa.Column('behandlung_id', sa.Integer(), nullable=True),
    sa.Column('tierarzt', sa.String(length=100), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['behandlung_id'], ['rind_arzneimittel_anwendung.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('klauenpflege_befund',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('klauenpfleger', sa.String(length=100), nullable=True),
    sa.Column('befund', sa.String(length=100), nullable=True),
    sa.Column('schweregrad', sa.Integer(), nullable=True),
    sa.Column('behandelt', sa.Boolean(), nullable=True),
    sa.Column('behandlung_id', sa.Integer(), nullable=True),
    sa.Column('naechste_pflege', sa.Date(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['behandlung_id'], ['rind_arzneimittel_anwendung.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mlp_pruefung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('laktation_id', sa.Integer(), nullable=True),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('laktationstag', sa.Integer(), nullable=True),
    sa.Column('milchmenge_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fett_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('eiweiss_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('laktose_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('harnstoff_mg_dl', sa.Integer(), nullable=True),
    sa.Column('zellzahl_tsd', sa.Integer(), nullable=True),
    sa.Column('ecm_kg', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('fett_eiweiss_quotient', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('pruefer', sa.String(length=100), nullable=True),
    sa.Column('probenahme_morgen_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('probenahme_abend_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laktation_id'], ['laktation.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('laktation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('body_condition_score_trocken', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('body_condition_score_kalbung', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('body_condition_score_100d', sa.Numeric(precision=3, scale=2), nullable=True))
        batch_op.add_column(sa.Column('ketose_test_datum', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('ketose_ergebnis', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('milchfieber', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('labmagen', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('laktation', schema=None) as batch_op:
        batch_op.drop_column('labmagen')
        batch_op.drop_column('milchfieber')
        batch_op.drop_column('ketose_ergebnis')
        batch_op.drop_column('ketose_test_datum')
        batch_op.drop_column('body_condition_score_100d')
        batch_op.drop_column('body_condition_score_kalbung')
        batch_op.drop_column('body_condition_score_trocken')

    op.drop_table('mlp_pruefung')
    op.drop_table('klauenpflege_befund')
    op.drop_table('euter_gesundheit')
    op.drop_table('besamung')
    op.drop_table('weide_periode')
    op.drop_table('tankmilch_auswertung')
    # ### end Alembic commands ###
