"""Fehlende Tabellen: bank_import_config, buchungsschluessel, faktura, kontosaldo

Revision ID: c5d231268061
Revises: b3c4d5e6f7g8
Create Date: 2026-03-13 10:58:47.236703

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c5d231268061'
down_revision = 'b3c4d5e6f7g8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_import_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bank_name', sa.Text(), nullable=True),
    sa.Column('spalte_datum', sa.Integer(), nullable=False),
    sa.Column('spalte_valuta', sa.Integer(), nullable=True),
    sa.Column('spalte_betrag', sa.Integer(), nullable=False),
    sa.Column('spalte_text', sa.Integer(), nullable=False),
    sa.Column('spalte_referenz', sa.Integer(), nullable=True),
    sa.Column('trennzeichen', sa.Text(), nullable=True),
    sa.Column('datumsformat', sa.Text(), nullable=True),
    sa.Column('dezimaltrennzeichen', sa.Text(), nullable=True),
    sa.Column('kopfzeilen_ueberspringen', sa.Integer(), nullable=True),
    sa.Column('encoding', sa.Text(), nullable=True),
    sa.Column('vorzeichen_umkehren', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('buchungsschluessel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kuerzel', sa.Text(), nullable=False),
    sa.Column('bezeichnung', sa.Text(), nullable=False),
    sa.Column('buchungstext', sa.Text(), nullable=True),
    sa.Column('soll_klassen', sa.Text(), nullable=True),
    sa.Column('haben_klassen', sa.Text(), nullable=True),
    sa.Column('soll_konto_id', sa.Integer(), nullable=True),
    sa.Column('haben_konto_id', sa.Integer(), nullable=True),
    sa.Column('suchbegriffe', sa.Text(), nullable=True),
    sa.Column('sortierung', sa.Integer(), nullable=True),
    sa.Column('aktiv', sa.Boolean(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['haben_konto_id'], ['konto.id'], ),
    sa.ForeignKeyConstraint(['soll_konto_id'], ['konto.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('kuerzel')
    )
    op.create_table('kontosaldo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('konto_id', sa.Integer(), nullable=False),
    sa.Column('geschaeftsjahr', sa.Integer(), nullable=False),
    sa.Column('saldo_beginn', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('saldo_aktuell', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('summe_soll', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('summe_haben', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['konto_id'], ['konto.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('konto_id', 'geschaeftsjahr', name='uq_konto_geschaeftsjahr')
    )
    op.create_table('faktura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kunde_id', sa.Integer(), nullable=False),
    sa.Column('geschaeftsjahr', sa.Integer(), nullable=False),
    sa.Column('fakturanummer', sa.Text(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('faellig_am', sa.Date(), nullable=True),
    sa.Column('art', sa.Text(), nullable=False),
    sa.Column('betreff', sa.Text(), nullable=True),
    sa.Column('betrag_netto', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('haben_konto_id', sa.Integer(), nullable=True),
    sa.Column('forderung_konto_id', sa.Integer(), nullable=True),
    sa.Column('buchung_id', sa.Integer(), nullable=True),
    sa.Column('bezahlt_buchung_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('ist_vorlage', sa.Boolean(), nullable=False),
    sa.Column('vorlage_name', sa.Text(), nullable=True),
    sa.Column('notizen', sa.Text(), nullable=True),
    sa.Column('erstellt_von', sa.Integer(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('dokument_typ', sa.Text(), nullable=False),
    sa.Column('storno_von_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bezahlt_buchung_id'], ['buchung.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['buchung_id'], ['buchung.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['erstellt_von'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['forderung_konto_id'], ['konto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['haben_konto_id'], ['konto.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['storno_von_id'], ['faktura.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fakturanummer')
    )
    op.create_table('faktura_position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faktura_id', sa.Integer(), nullable=False),
    sa.Column('bezeichnung', sa.Text(), nullable=False),
    sa.Column('menge', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('einheit', sa.Text(), nullable=True),
    sa.Column('einzelpreis', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('betrag', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sortierung', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faktura_id'], ['faktura.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rechnungsposition')
    op.drop_table('rechnung')
    op.drop_table('kategorie')
    with op.batch_alter_table('konto', schema=None) as batch_op:
        batch_op.alter_column('bezeichnung',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.alter_column('aktiv',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rolle',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=30),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('rolle',
               existing_type=sa.String(length=30),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    with op.batch_alter_table('kunde', schema=None) as batch_op:
        batch_op.alter_column('aktiv',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))

    with op.batch_alter_table('konto', schema=None) as batch_op:
        batch_op.alter_column('bezeichnung',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('rechnungsposition',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rechnung_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('beschreibung', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('menge', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('einheit', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('einzelpreis', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('mwst_satz', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.Column('netto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.Column('mwst', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('brutto', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['rechnung_id'], ['rechnung.id'], name=op.f('rechnungsposition_rechnung_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('rechnungsposition_pkey'))
    )
    op.create_table('kategorie',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('beschreibung', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('farbe', sa.VARCHAR(length=7), autoincrement=False, nullable=True),
    sa.Column('erstellt_am', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('kategorie_pkey'))
    )
    op.create_table('rechnung',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nummer', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('kunde_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('datum', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('faellig_am', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('netto_gesamt', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('mwst_gesamt', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('brutto_gesamt', sa.NUMERIC(precision=12, scale=2), autoincrement=False, nullable=True),
    sa.Column('notiz', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('erstellt_am', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['kunde_id'], ['kunde.id'], name=op.f('rechnung_kunde_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('rechnung_pkey')),
    sa.UniqueConstraint('nummer', name=op.f('rechnung_nummer_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('faktura_position')
    op.drop_table('faktura')
    op.drop_table('kontosaldo')
    op.drop_table('buchungsschluessel')
    op.drop_table('bank_import_config')
    # ### end Alembic commands ###
