"""milchvieh modul: rind, tierbewegung, laktation, arzneimittel, impfung + betrieb modul_milchvieh

Revision ID: d66b05281647
Revises: 8286c91bc26c
Create Date: 2026-03-14 18:05:10.296666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd66b05281647'
down_revision = '8286c91bc26c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ohrmarke', sa.String(length=20), nullable=False),
    sa.Column('ohrmarke_2', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('rasse', sa.String(length=100), nullable=True),
    sa.Column('geschlecht', sa.String(length=1), nullable=True),
    sa.Column('geburtsdatum', sa.Date(), nullable=True),
    sa.Column('geburtsgewicht_kg', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('mutter_ohrmarke', sa.String(length=20), nullable=True),
    sa.Column('vater_hb_nr', sa.String(length=50), nullable=True),
    sa.Column('herkunft_betrieb', sa.String(length=200), nullable=True),
    sa.Column('herkunft_land', sa.String(length=2), nullable=True),
    sa.Column('eingang_datum', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('nutzungsart', sa.String(length=20), nullable=True),
    sa.Column('abgang_datum', sa.Date(), nullable=True),
    sa.Column('abgangsursache', sa.String(length=100), nullable=True),
    sa.Column('ama_gemeldet', sa.Boolean(), nullable=True),
    sa.Column('ama_meldedatum', sa.Date(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rind', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rind_ohrmarke'), ['ohrmarke'], unique=True)

    op.create_table('laktation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('laktationsnummer', sa.Integer(), nullable=True),
    sa.Column('kalbedatum', sa.Date(), nullable=True),
    sa.Column('kalbeverlauf', sa.String(length=50), nullable=True),
    sa.Column('kalb_ohrmarke', sa.String(length=20), nullable=True),
    sa.Column('kalb_geschlecht', sa.String(length=1), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('trockenstell_datum', sa.Date(), nullable=True),
    sa.Column('laktations_ende', sa.Date(), nullable=True),
    sa.Column('ist_aktiv', sa.Boolean(), nullable=True),
    sa.Column('milch_305_tage_kg', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fett_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('eiweiss_prozent', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('zellzahl_tsd', sa.Integer(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rind_arzneimittel_anwendung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('beginn', sa.Date(), nullable=False),
    sa.Column('ende', sa.Date(), nullable=True),
    sa.Column('arzneimittel_name', sa.String(length=200), nullable=False),
    sa.Column('wirkstoff', sa.String(length=200), nullable=True),
    sa.Column('zulassungsnummer', sa.String(length=50), nullable=True),
    sa.Column('charge', sa.String(length=100), nullable=True),
    sa.Column('dosierung', sa.String(length=200), nullable=True),
    sa.Column('verabreichungsart', sa.String(length=50), nullable=True),
    sa.Column('behandlungsdauer_tage', sa.Integer(), nullable=True),
    sa.Column('anzahl_tiere', sa.Integer(), nullable=True),
    sa.Column('diagnose', sa.String(length=200), nullable=True),
    sa.Column('tierarzt_name', sa.String(length=200), nullable=True),
    sa.Column('rezept_nr', sa.String(length=50), nullable=True),
    sa.Column('ist_antibiotikum', sa.Boolean(), nullable=True),
    sa.Column('wartezeit_milch_tage', sa.Integer(), nullable=True),
    sa.Column('wartezeit_milch_ende', sa.Date(), nullable=True),
    sa.Column('wartezeit_fleisch_tage', sa.Integer(), nullable=True),
    sa.Column('wartezeit_fleisch_ende', sa.Date(), nullable=True),
    sa.Column('beleg_nr', sa.String(length=50), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rind_impfung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('impfstoff', sa.String(length=200), nullable=True),
    sa.Column('krankheit', sa.String(length=100), nullable=True),
    sa.Column('charge', sa.String(length=100), nullable=True),
    sa.Column('verabreichungsart', sa.String(length=50), nullable=True),
    sa.Column('tierarzt', sa.String(length=200), nullable=True),
    sa.Column('naechste_impfung', sa.Date(), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('aktualisiert_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tierbewegung',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rind_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.Date(), nullable=False),
    sa.Column('typ', sa.String(length=30), nullable=False),
    sa.Column('gegenpartei_betrieb', sa.String(length=200), nullable=True),
    sa.Column('gegenpartei_land', sa.String(length=2), nullable=True),
    sa.Column('schlachthof', sa.String(length=200), nullable=True),
    sa.Column('gewicht_kg', sa.Numeric(precision=6, scale=1), nullable=True),
    sa.Column('preis', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ama_gemeldet', sa.Boolean(), nullable=True),
    sa.Column('ama_meldedatum', sa.Date(), nullable=True),
    sa.Column('beleg_nr', sa.String(length=50), nullable=True),
    sa.Column('bemerkung', sa.Text(), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['rind_id'], ['rind.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('betrieb', schema=None) as batch_op:
        batch_op.add_column(sa.Column('modul_milchvieh', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('betrieb', schema=None) as batch_op:
        batch_op.drop_column('modul_milchvieh')

    op.drop_table('tierbewegung')
    op.drop_table('rind_impfung')
    op.drop_table('rind_arzneimittel_anwendung')
    op.drop_table('laktation')
    with op.batch_alter_table('rind', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rind_ohrmarke'))

    op.drop_table('rind')
    # ### end Alembic commands ###
