"""feat: SSO-Token-Tabelle

Revision ID: e5578613fbba
Revises: 22a8ef55648f
Create Date: 2026-03-17 21:40:23.278284

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5578613fbba'
down_revision = '22a8ef55648f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sso_token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('ziel_instanz', sa.String(length=50), nullable=True),
    sa.Column('erstellt_am', sa.DateTime(), nullable=True),
    sa.Column('gueltig_bis', sa.DateTime(), nullable=False),
    sa.Column('verwendet', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sso_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sso_token_token'), ['token'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sso_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sso_token_token'))

    op.drop_table('sso_token')
    # ### end Alembic commands ###
